name: ML CI/CD Pipeline

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ml-cicd-pipeline

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Unit Tests
      run: pytest tests/

    - name: Train Model
      run: python model/train.py

    - name: Evaluate Model
      run: python model/evaluate.py

  deploy:
    needs: test-and-train
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ml-api .

    - name: Run container (local test)
      run: docker run -d -p 8000:8000 ml-api
